### ISSUE TITLE
calcul distance entre deux points

### ISSUE THREAD

**Issue by py-b** [sebastien-bugzilla/BatiOsm#1]
Bonjour,

J'ai un doute sur la fonction qui calcule la distance (euclidenne) entre deux points.

Comme ce sont des angles et non des coordonnées dans le plan, il faudrait plutôt utiliser une formule avec sinus et cosinus sur des angles préalablement convertis en radians.

the-knife (the_knife sur osm)

**Comment by julien-noblet** [comment]
A regarder ici : https://github.com/rory/python-osm/blob/master/osm.py 

``` python
def distance(self, other):
        """
        Returns the distance between this point the other in metres
        """
        lat1=float(self.lat) * math.pi / 180
        lat2=float(other.lat) * math.pi / 180
        lon1=float(self.lon) * math.pi / 180
        lon2=float(other.lon) * math.pi / 180
        dist = math.atan(math.sqrt(math.pow(math.cos(lat2)*math.sin(abs(lon1-lon2)),2) + math.pow(math.cos(lat1)*math.sin(lat2) - math.sin(lat1)*math.cos(lat2)*math.cos(lon1-lon2),2)) / (math.sin(lat1)*math.sin(lat2) + math.cos(lat1)*math.cos(lat2)*math.cos(lon1-lon2)))
        dist *= 6372795 # convert from radians to meters
        return dist
```

**Comment by sebastien-bugzilla** [comment]
Salut
Oui bien sûr c'était une approximation. Pour moi je voulais faire simple (car  cette fonction est beaucoup utilisée) et dans la mesure où on ne cherche pas la distance en elle même. On veut juste identifier le batiment le plus proche.
Mais bon si on peut avoir la distance exacte et que le calcul ne prend pas énormément plus de temps pourquoi pas...

**Comment by py-b** [comment]
Avoir une distance en mètres permettra peut-être de paramétrer plus facilement la tolérance pour le rapprochement, s'il y en a une (je n'ai pas lu tout le code, je ne connais pas bien le langage python d'ailleurs). ;-)

**Comment by julien-noblet** [comment]
Je viens de faire quelques tests, cela multiplie par 3 le temps de calcul :/
Sur une petite commune (le Givre en Vendée,  3895 noeuds et 708 bâtiments ) on a une moyenne de 4m d'écarts. et un max de 24m ce qui reste raisonnable

On doit pouvoir trouver un compromis du genre : 

``` python
 math.sqrt(d_lat**2 + d_lon**2)* coef
```

avec un coef = 6372795 \* math.pi / 180 on peux aussi mettre un correcteur pour corriger la latitude.
